### ISSUE TITLE
收集音乐素材

### ISSUE THREAD

**Issue by Nukepayload2** [Nukepayload2/GcXaMap3DProjMgr#1]
需要收集:
 - [x] 片头曲
 - [x] 片尾曲
 - [x] 音效
 - [x] 每段剧情的背景音乐

时间限制: 4 天
开始时间: 2018-11-12

**Comment by ivuu** [comment]
音效大全，已分享在百度云上
链接：https://pan.baidu.com/s/1_qZrICXwui9rmk9xSR5-Hg 密码：fvl5

**Comment by Nukepayload2** [comment]
@ivuu 好的，辛苦了。音乐我打算采纳第二首，因为第一首一听就是圣诞节的。第二首打算剪成两段用，或者配合我自己找的备用音乐使用。

**Comment by Nukepayload2** [comment]
第二首会在第一次排练发布的预览版使用。如果上级检查没问题，这个任务才算完全完成。

**Comment by ivuu** [comment]
好的，当初预想是 年会刚过圣诞节不久。不过将第一首裁剪成两段也是可以的~

**Comment by Nukepayload2** [comment]
@ivuu 那预告片我就用第一首。
